"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const product_controller_1 = require("./product.controller");
const auth_1 = require("../../middleware/auth");
const router = (0, express_1.Router)();
router.use(auth_1.requireAuth);
router.post('/', product_controller_1.ProductController.create);
router.get('/', product_controller_1.ProductController.list);
router.get('/:id', product_controller_1.ProductController.getById);
router.put('/:id', product_controller_1.ProductController.update);
router.delete('/:id', product_controller_1.ProductController.delete);
exports.default = router;
